
export const TOP_LEVEL_PAGES = {
  PDF_ANALYSIS: 'PDF_ANALYSIS',
  VALIDATION: 'VALIDATION',
  MODEL_CHECKER: 'MODEL_CHECKER',
} as const;

export const VALIDATION_PAGES = {
  COMPARISON: 'COMPARISON',
  VALIDATION: 'VALIDATION',
  QNA: 'QNA',
  DOC_DIFF: 'DOC_DIFF',
} as const;

export const MODEL_CHECKER_PAGES = {
  QAQC: 'QAQC',
  MIDP_CHECK: 'MIDP_CHECK',
  PARAMETER_CHECK: 'PARAMETER_CHECK',
  CLASH_ANALYSIS: 'CLASH_ANALYSIS',
} as const;


export const STRINGS = {
  appTitle: 'Intelligent Document Analyzer',
  validationSuitePage: 'Validation',
  modelCheckerPage: 'Model Checker',
  analysisPage: 'PDF Analysis',
  comparisonPage: 'Data Verification',
  validationPage: 'Bulk Validation',
  qaqcPage: 'QA/QC',
  qnaPage: 'Document Q&A',
  docDiffPage: 'Visual Comparison',
  midpCheckPage: 'MIDP Check',
  parameterCheckPage: 'Parameter Checker',
  clashAnalysisPage: 'Clash Analysis',
  qaqc2Page: 'QA QC-2',
  uploadPdf: 'Upload a PDF to analyze it',
  uploadExcel: 'Upload an Excel file to validate against the PDF',
  uploadButton: 'Choose a file',
  analyzeButton: 'Start Analysis',
  analyzing: 'Analyzing...',
  analysisResultTitle: 'Document Analysis Results:',
  dropHere: 'or drag and drop it here',
  noFileSelected: 'No file selected',
  compareData: 'Verify Data Against PDF',
  enterDataToCompare: 'Enter a statement or data to verify...',
  compareButton: 'Verify',
  comparing: 'Verifying...',
  validateButton: 'Start Validation',
  validating: 'Validating...',
  comparisonResultTitle: 'Verification Result:',
  validationResultTitle: 'Validation Results:',
  pleaseAnalyzeFirst: 'Please analyze a PDF file first on the Analysis page.',
  errorOccurred: 'An error occurred. Please try again.',
  pdfExtractionError: 'An error occurred while extracting text from the PDF.',
  fileLabel: 'Selected file:',
  comparedWith: 'Verified against:',
  footerText: 'Powered by Gemini API.',
  extractionOptions: 'Extraction Options',
  preserveFormatting: 'Preserve Formatting',
  extractFromImages: 'Extract Text from Images (OCR)',
  exportExcel: 'Export as Excel',
  exportPdf: 'Export as PDF',
  askAnything: 'Ask anything about the document...',
  askButton: 'Ask',
  asking: 'Thinking...',
  answerTitle: 'Answer:',
  speakButtonTitle: 'Ask with your voice',
  listening: 'Listening...',
  playAnswer: 'Play Answer',
  speechRecognitionNoSpeech: "I couldn't hear anything. Please make sure your microphone is unmuted and try again.",
  speechRecognitionGenericError: "A speech recognition error occurred. Please check your microphone permissions and try again.",
  // Welcome Page Strings
  welcomeTitle: 'Welcome to the AI World',
  welcomeSubtitle: 'AI is Here and Now',
  getStarted: 'Get Started',
  // MIDP Check Strings
  uploadAccData: 'Upload ACC Data',
  uploadMidpData: 'Upload MIDP Data',
  compareFiles: 'Compare Files',
  comparingFiles: 'Comparing...',
  comparisonResults: 'Comparison Results',
  exportResults: 'Export Results',
  presentInBoth: 'Present in both',
  missingInAcc: 'Missing in ACC',
  extraInAcc: 'Extra in ACC',
  matched: 'Matched',
  missing: 'Missing',
  extra: 'Extra',
  accFile: 'ACC Data File',
  midpFile: 'MIDP Data File',
  // Parameter Checker Strings
  uploadParamFile: 'Upload a file to check parameter completion',
  analyzeParameters: 'Analyze Parameters',
  analyzingParameters: 'Analyzing Parameters...',
  parameterAnalysisTitle: 'Parameter Completion Analysis',
  parameter: 'Parameter',
  filled: 'Filled',
  empty: 'Empty',
  percentageFilled: '% Filled',
  fullDataTable: 'Full Data Table',
  filters: 'Filters',
  clearFilters: 'Clear Filters',
  noResultsForFilter: 'No results match the current filters.',
  filterByParameter: 'Filter by parameter name...',
  allParameters: 'All Parameters',
  analysisTab: 'Analysis',
  // QA/QC Page Strings
  qaqcSelectColumns: 'Select Columns to Verify',
  qaqcFileName: 'File Name',
  qaqcProjectUnits: 'Project Units',
  qaqcSurveyPoint: 'Survey Point',
  qaqcProjectBasePoint: 'Project Base Point',
  qaqcRvtLinkPinned: 'RVT Link is Pinned',
  qaqcRevitLinksPath: 'Revit Links Path',
  qaqcImportedCad: 'Imported CAD',
  qaqcLevelsGridsPinned: 'Levels-Grids / Element Is Pinned',
  qaqcCategoryWorksetName: 'Category/Workset Name',
  qaqcStartingViewName: 'Starting View Name',
  qaqcNavisworksViewName: 'Navisworks View Name',
  qaqcViewsNotInSheets: 'Views Not in Sheets',
  qaqcRunAnalysis: 'Run QA/QC Analysis',
  qaqcAnalyzing: 'Running Analysis...',
  qaqcResultsTitle: 'QA/QC Analysis Results',
  summaryTab: 'Summary',
  detailedResultsTab: 'Detailed Results',
  crsTab: 'CRS',
  fileNameCheckResultsTitle: 'File Name Check Results',
  projectUnitsCheckResultsTitle: 'Project Units Check Results',
  surveyPointCheckResultsTitle: 'Survey Point Check Results',
  projectBasePointCheckResultsTitle: 'Project Base Point Check Results',
  rvtLinkPinnedCheckResultsTitle: 'RVT Link is Pinned Check Results',
  qaqcRevitLinksPathCheckResultsTitle: 'Revit Links Path Check Results',
  qaqcImportedCadCheckResultsTitle: 'Imported CAD Check Results',
  qaqcLevelsPinnedCheckResultsTitle: 'Levels Pinned Check Results',
  qaqcGridsPinnedCheckResultsTitle: 'Grids Pinned Check Results',
  categoryWorksetNameCheckResultsTitle: 'Workset Naming Check Results',
  startingViewNameCheckResultsTitle: 'Starting View Name Check Results',
  qaqcNavisworksViewNameCheckResultsTitle: 'Navisworks View Name Check Results',
  qaqcViewsNotInSheetsCheckResultsTitle: 'Views Not in Sheets Check Results',
  uploadExcelForQaqc: 'Upload an Excel file to perform QA/QC checks.',
  // Clash Analysis
  clashAnalysisUpload: 'Upload Navisworks Clash Report (Excel)',
  clashAnalyzeButton: 'Analyze Clashes',
  // Doc Diff
  diffCompareButton: 'Compare Documents',
  diffOriginalFile: 'Original Document',
  diffNewFile: 'Modified Document',
  diffSummaryTitle: 'Comparison Summary',
  // QA QC-2 Strings
  qaqc2UploadPdf: 'Upload PDF Rules',
  qaqc2UploadCsv: 'Upload CSV Data',
  qaqc2Compare: 'Compare Rules vs Data',
  // Weekly Updates Strings
  uploadWeeklyExcel: 'Upload Weekly Delivery Excel',
  deliveryCycle: 'Friday starts a new delivery cycle. Thursday is the deadline.',
  analyzeWeekly: 'Analyze Weekly Updates',
  weeklySummary: 'Weekly Delivery Summary',
};
